<?php
CREATE TABLE User1 (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
genre VARCHAR(50) NOT NULL,
pages SMALLINT(10) UNSIGNED,
year SMALLINT(6) UNSIGNED
)
    ?>